package ESDChatBox.plugin;

/*Generated by MPS */

import java.io.Serializable;

public class ChatMessage implements Serializable {
  protected static final long serialVersionUID = 1112122200L;
  /*package*/ static final int WHOISIN = 0;
  /*package*/ static final int MESSAGE = 1;
  /*package*/ static final int LOGOUT = 2;
  /*package*/ static final int COPYNODE = 3;
  private int type;
  private String message;
  /*package*/ ChatMessage(int type, String message) {
    this.type = type;
    this.message = message;
  }
  /*package*/ int getType() {
    return type;
  }
  /*package*/ String getMessage() {
    return message;
  }
}
