package ESDChatBox.plugin;

/*Generated by MPS */

import jetbrains.mps.workbench.action.BaseAction;
import javax.swing.Icon;
import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.ide.actions.MPSCommonDataKeys;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.actionSystem.CommonDataKeys;
import org.jetbrains.annotations.NotNull;
import com.mbeddr.mpsutil.serializer.xml.serializer.NodeSerializer;

public class CopyNodeToClipBoardAction_Action extends BaseAction {
  private static final Icon ICON = null;

  public CopyNodeToClipBoardAction_Action() {
    super("Copy Node Info To ESD Chat", "", ICON);
    this.setIsAlwaysVisible(false);
    this.setExecuteOutsideCommand(false);
  }
  @Override
  public boolean isDumbAware() {
    return true;
  }
  @Override
  protected boolean collectActionData(AnActionEvent event, final Map<String, Object> _params) {
    if (!(super.collectActionData(event, _params))) {
      return false;
    }
    {
      SNode node = event.getData(MPSCommonDataKeys.NODE);
      if (node == null) {
        return false;
      }
    }
    {
      Project p = event.getData(CommonDataKeys.PROJECT);
      if (p == null) {
        return false;
      }
    }
    return true;
  }
  @Override
  public void doExecute(@NotNull final AnActionEvent event, final Map<String, Object> _params) {
    NodeSerializer s = new NodeSerializer(event.getData(MPSCommonDataKeys.NODE), true, "_");
    ChatMessage message = new ChatMessage(ChatMessage.MESSAGE, "_____" + s.getXMLAsString());
    ClientGUI.client.sendMessage(message);
  }
}
