package ESDChatBox.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;

public class CopyNodeChatEditorActionGroup_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "ESDChatBox.plugin.CopyNodeChatEditorActionGroup_ActionGroup";
  public CopyNodeChatEditorActionGroup_ActionGroup() {
    super("CopyNodeChatEditorActionGroup", ID);
    this.setIsInternal(false);
    this.setPopup(false);
    CopyNodeChatEditorActionGroup_ActionGroup.this.addAction("ESDChatBox.plugin.CopyNodeToClipBoardAction_Action");
  }
}
