package ESDChatBox.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.tool.GeneratedTool;
import javax.swing.Icon;
import javax.swing.JPanel;
import jetbrains.mps.smodel.SNode;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.wm.ToolWindowAnchor;
import javax.swing.JComponent;

public class ESD_Chat_Window_Tool extends GeneratedTool {
  private static final Icon ICON = null;
  private JPanel m_panal;
  private SNode node;
  public ESD_Chat_Window_Tool(Project project) {
    super(project, "ESD Chat Window", null, ICON, ToolWindowAnchor.BOTTOM, false);
  }
  public void init(Project project) {
    super.init(project);
    ESD_Chat_Window_Tool.this.m_panal = new ClientGUI("localhost", "1500");
  }
  public JComponent getComponent() {
    return ESD_Chat_Window_Tool.this.m_panal;
  }
}
