package ESDChatBox.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;

public class ESDChatGUIActionGroup_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "ESDChatBox.plugin.ESDChatGUIActionGroup_ActionGroup";
  public ESDChatGUIActionGroup_ActionGroup() {
    super("ESD Chat Application", ID);
    this.setIsInternal(false);
    this.setPopup(true);
    ESDChatGUIActionGroup_ActionGroup.this.addAction("ESDChatBox.plugin.StartESDChatClient_Action");
    ESDChatGUIActionGroup_ActionGroup.this.addAction("ESDChatBox.plugin.StartESDChatServerAction_Action");
  }
}
