package ESDChatBox.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;
import jetbrains.mps.ide.actions.ModelActions_ActionGroup;
import jetbrains.mps.ide.actions.NodeActions_ActionGroup;
import java.util.List;
import jetbrains.mps.plugins.actions.BaseKeymapChanges;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class ESDChatBox_ApplicationPlugin extends BaseApplicationPlugin {
  private PluginId myId = PluginId.getId("ESDChatBox");
  public ESDChatBox_ApplicationPlugin() {
  }
  public PluginId getId() {
    return myId;
  }
  public void createGroups() {
    // actions w/o parameters 
    addAction(new CopyNodeToClipBoardAction_Action());
    addAction(new PasteCopiedNodeAction_Action());
    addAction(new StartESDChatClient_Action());
    addAction(new StartESDChatServerAction_Action());
    // groups 
    addGroup(new CopyNodeChatEditorActionGroup_ActionGroup());
    addGroup(new ESDChatGUIActionGroup_ActionGroup());
    addGroup(new PasteNodeChatEditorActionGroup_ActionGroup());
  }
  public void adjustRegularGroups() {
    insertGroupIntoAnother(ESDChatGUIActionGroup_ActionGroup.ID, "ToolsMenu", null);
    insertGroupIntoAnother(PasteNodeChatEditorActionGroup_ActionGroup.ID, ModelActions_ActionGroup.ID, ModelActions_ActionGroup.LABEL_ID_paste);
    insertGroupIntoAnother(CopyNodeChatEditorActionGroup_ActionGroup.ID, NodeActions_ActionGroup.ID, NodeActions_ActionGroup.LABEL_ID_copy);
  }
  public List<BaseKeymapChanges> initKeymaps() {
    List<BaseKeymapChanges> res = ListSequence.fromList(new ArrayList<BaseKeymapChanges>());
    ListSequence.fromList(res).addElement(new PasteFromESDChat_KeymapChanges());
    return res;
  }
}
