package ESDChatBox.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.BaseKeymapChanges;
import com.intellij.openapi.actionSystem.Shortcut;
import com.intellij.openapi.actionSystem.KeyboardShortcut;
import javax.swing.KeyStroke;

public class PasteFromESDChat_KeymapChanges extends BaseKeymapChanges {
  public PasteFromESDChat_KeymapChanges() {
    // simple 
    addSimpleShortcut("ESDChatBox.plugin.PasteCopiedNodeAction_Action", getShortcut("ctrl alt shift P"));
    // simple parameterized 
    // complex 
  }
  public String getScheme() {
    return "Default for XWin";
  }
  public static Shortcut getShortcut(String stroke) {
    return new KeyboardShortcut(KeyStroke.getKeyStroke(stroke), null);
  }
}
