package ESDChatBox.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;

public class PasteNodeChatEditorActionGroup_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "ESDChatBox.plugin.PasteNodeChatEditorActionGroup_ActionGroup";
  public PasteNodeChatEditorActionGroup_ActionGroup() {
    super("PasteNodeChatEditorActionGroup", ID);
    this.setIsInternal(false);
    this.setPopup(false);
    PasteNodeChatEditorActionGroup_ActionGroup.this.addAction("ESDChatBox.plugin.PasteCopiedNodeAction_Action");
  }
}
