package ESDChatBox.plugin;

/*Generated by MPS */

import jetbrains.mps.workbench.action.BaseAction;
import javax.swing.Icon;
import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.actionSystem.CommonDataKeys;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.plugins.projectplugins.ProjectPluginManager;

public class StartESDChatClient_Action extends BaseAction {
  private static final Icon ICON = null;

  public StartESDChatClient_Action() {
    super("Start ESD Chat Client", "", ICON);
    this.setIsAlwaysVisible(false);
    this.setExecuteOutsideCommand(false);
  }
  @Override
  public boolean isDumbAware() {
    return true;
  }
  @Override
  protected boolean collectActionData(AnActionEvent event, final Map<String, Object> _params) {
    if (!(super.collectActionData(event, _params))) {
      return false;
    }
    {
      Project p = event.getData(CommonDataKeys.PROJECT);
      if (p == null) {
        return false;
      }
    }
    return true;
  }
  @Override
  public void doExecute(@NotNull final AnActionEvent event, final Map<String, Object> _params) {
    event.getData(CommonDataKeys.PROJECT).getComponent(ProjectPluginManager.class).getTool(ESD_Chat_Window_Tool.class).init(event.getData(CommonDataKeys.PROJECT));
    event.getData(CommonDataKeys.PROJECT).getComponent(ProjectPluginManager.class).getTool(ESD_Chat_Window_Tool.class).openTool(true);
    event.getData(CommonDataKeys.PROJECT).getComponent(ProjectPluginManager.class).getTool(ESD_Chat_Window_Tool.class).setAvailable(true);
  }
}
